# 고대의 성에서 🏰
숲을 지나 고대의 성에 도착한 당신. 성을 정복하기 위해 최종 도전 과제를 해결해야 합니다.

# [문제 1] **"마법 진주"**
### 원하는만큼 마법 진주를 만들어 낼 수 있는 항아리가 있습니다. 변수 `n`에 숫자를 저장하고, `1`부터 `n`까지의 합을 출력하세요.

In [3]:
import numpy as np

number = [1,2,3,4,5]
n = np.sum(number)
print(n)

15


# [문제 2] **"왕의 암호"**
### `kingdom` 변수에 여러개의 문자를 입력받아, 각 단어의 첫 글자만 대문자로 출력하세요.
### `kingdom`의 문자열에는 `queen`,`password`,`ozcodingschool`이 기본적으로 입력되어야 하며, 콤마(,)로 단어를 구분합니다.

In [10]:
#kingdom 변수에 주어진 문자열
kingdom = 'queen,password,ozcodingschool'

#split(,) 를 이용하여 콤마(,) 로 단어를 구분
kingdom.split(',')

#단어를 구분 한것을 편하게 a 에 하달
a = kingdom.split(',')

# b , c , d 에 한단어씩 슬라이싱 과 .upper() 을 이용 하여 첫번째 글자만 대문자로 출력
b = (a[0][0].upper())
c = (a[1][0].upper())
d = (a[2][0].upper())

#결과
print(b)
print(c)
print(d)

Q
P
O


# [문제 3] **"성의 열쇠"**
### `5x5`크기의 배열로 숫자 1부터 25까지를 출력하세요.

In [3]:
'''
ne.arange() 함수로 주어진 범위에서 지정된 각격으로 숙차적인
값들로 이루어진 배열을 생성합니다 1 부터 26미만의 숫자로 배열


'''
a = np.arange(1,26).reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# [문제 4] **"최고의 마법사"**
### 여러 숫자를 입력받아 가장 큰 숫자와 가장 작은 숫자를 출력하세요.


# [문제 5] **"숲 속의 빛나는 숫자"**
### 주어진 숫자가 소수인지 판별하세요.

# [문제 6] **"왕의 보물 상자"**
### 리스트 `[10, 20, 15, 25, 30]`에서 20 이상인 숫자만 출력하세요.

# [문제 7] **"마법사의 나침반"**
### 좌표를 입력받아 북쪽, 남쪽, 동쪽, 서쪽으로 나누어 출력하세요.

# [문제 8] **"숲의 보물 지도"**
### 문자열 `Tresure Hunt`에서 공백을 제거하고 길이를 계산하세요.

# [문제 9] **"숲 속의 마법사 대결"**
### 사용자로부터 두 숫자를 입력받아 최대공약수를 계산하세요.

# [문제 10] **"성의 마지막 방"**
### 리스트에 있는 숫자들을 모두 더한 값이 100 이상이면 `열림`을 출력하고, 그렇지 않으면 `닫힘`을 출력하세요.